name: Lint-Test-Build

on: [pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Install ğŸ”§
        run: npm install

      - name: Lint ğŸ•µï¸â€â™€ï¸
        run: npm run lint

      - name: Test ğŸ›
        run: npm run test

      - name: Build ğŸ“¦
        run: npm run build
