name: Lint-Test-Build

on: [pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
        BASE_PATH: ci-cd-demo
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Install ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm install

      - name: Lint ğŸ•µï¸â€â™€ï¸
        run: npm run lint

      - name: Test ğŸ
        run: npm run test

      - name: Build ğŸ“¦
        run: npm run build
